// GENERATED by scripts/resolve-shelf-photos.mjs — do not edit.
//
// Photographs for the home mosaic's two newest shelves. Every URL is a licensed
// stock photograph of similar goods, never a photograph of anything Sambramo has
// sourced — the same distinction every product tile and the decor gallery make,
// and the reason the shelves these front are seeded with image_source 'stock'.
//
// Re-run the resolver rather than editing this file:
//   node scripts/resolve-shelf-photos.mjs --dry-run
//   node scripts/resolve-shelf-photos.mjs
//
// Resolved 2026-08-17 from pexels.

export const GENERATED_SHELF_PHOTOS = {
  "handmade": [
    {
      "url": "https://images.pexels.com/photos/30348949/pexels-photo-30348949.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "A vibrant set of traditional wooden nesting dolls, handcrafted with intricate designs and bright colors.",
      "credit": "Photo by Ranjita SG on Pexels",
      "query": "channapatna wooden toys indian handicraft"
    },
    {
      "url": "https://images.pexels.com/photos/34545851/pexels-photo-34545851.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "A variety of traditional clay and metal pots beautifully arranged in a market setting.",
      "credit": "Photo by Ashok  Gajjar on Pexels",
      "query": "indian terracotta clay pottery handmade"
    },
    {
      "url": "https://images.pexels.com/photos/15755947/pexels-photo-15755947.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Golden sculptures displayed at vibrant outdoor market, showcasing traditional artistry and culture.",
      "credit": "Photo by Swastik Arora on Pexels",
      "query": "indian brass handicraft traditional decor"
    },
    {
      "url": "https://images.pexels.com/photos/28617395/pexels-photo-28617395.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Artisanal woven baskets and handcrafted bird nests for sale at a cultural market.",
      "credit": "Photo by Rajib Chowdhury on Pexels",
      "query": "handwoven jute basket indian craft"
    }
  ],
  "eco": [
    {
      "url": "https://images.pexels.com/photos/1374879/pexels-photo-1374879.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Bright and fresh houseplants in stylish pots, enhancing indoor greenery.",
      "credit": "Photo by Khanh Nguyen on Pexels",
      "query": "money plant indoor pot gift"
    },
    {
      "url": "https://images.pexels.com/photos/4751975/pexels-photo-4751975.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Close-up of hands planting a peace lily in a terracotta pot with gloves.",
      "credit": "Photo by https://kaboompics.com/ on Pexels",
      "query": "peace lily plant white ceramic pot"
    },
    {
      "url": "https://images.pexels.com/photos/13677856/pexels-photo-13677856.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Abundant clusters of lucky bamboo plants tied with red ribbons for decorative purposes.",
      "credit": "Photo by Markus Winkler on Pexels",
      "query": "lucky bamboo plant indoor decor"
    },
    {
      "url": "https://images.pexels.com/photos/1556764/pexels-photo-1556764.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "A collection of potted succulents in terracotta pots on a wooden table.",
      "credit": "Photo by Dương Nhân on Pexels",
      "query": "succulent plant terracotta pot gift"
    }
  ],
  "silk": [
    {
      "url": "https://images.pexels.com/photos/10317113/pexels-photo-10317113.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Close-up of a traditional Kanchipuram silk saree, showcasing intricate patterns and vibrant colors.",
      "credit": "Photo by Sharath G. on Pexels",
      "query": "silk saree gold zari indian traditional"
    },
    {
      "url": "https://images.pexels.com/photos/22735414/pexels-photo-22735414.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Indian woman in vibrant traditional attire, smiling near a window indoors.",
      "credit": "Photo by Fotographiya Wedding Photography on Pexels",
      "query": "indian bride silk saree wedding"
    },
    {
      "url": "https://images.pexels.com/photos/20181020/pexels-photo-20181020.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Close-up of intricate gold and silver brocade fabric showcasing detailed patterns.",
      "credit": "Photo by Olga Kovalski on Pexels",
      "query": "silk fabric texture gold thread"
    },
    {
      "url": "https://images.pexels.com/photos/8750030/pexels-photo-8750030.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Women wearing vibrant sarees indoors, highlighting traditional Indian attire and culture.",
      "credit": "Photo by Anastasia  Shuraeva on Pexels",
      "query": "draped silk saree pallu detail"
    }
  ],
  "weaves": [
    {
      "url": "https://images.pexels.com/photos/23494589/pexels-photo-23494589.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Closeup of hands weaving on a loom in a black and white setting, showcasing traditional craftsmanship.",
      "credit": "Photo by Duc Nguyen on Pexels",
      "query": "indian handloom weaving loom weaver"
    },
    {
      "url": "https://images.pexels.com/photos/11733651/pexels-photo-11733651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Close-up of a stack of neatly folded green linens highlighting their texture and neatness.",
      "credit": "Photo by Ruslan Rozanov on Pexels",
      "query": "handloom cotton saree folded stack"
    },
    {
      "url": "https://images.pexels.com/photos/57565/pexels-photo-57565.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Detailed collection of traditional Indian block print patterns, highlighting cultural artistry.",
      "credit": "Photo by Jatin Baghel on Pexels",
      "query": "indian textile block print fabric"
    },
    {
      "url": "https://images.pexels.com/photos/6876968/pexels-photo-6876968.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Vibrant yellow silk threads drying in a traditional textile factory.",
      "credit": "Photo by Quang Nguyen Vinh on Pexels",
      "query": "silk thread spools weaving workshop"
    }
  ],
  "carving": [
    {
      "url": "https://images.pexels.com/photos/38016310/pexels-photo-38016310.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Detailed stone carvings depicting historical figures at Halebeedu Temple, India.",
      "credit": "Photo by Nikhil Shinde on Pexels",
      "query": "stone carving sculpture indian temple"
    },
    {
      "url": "https://images.pexels.com/photos/30563520/pexels-photo-30563520.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Close-up of an artisan's hands skillfully carving wood in a traditional Moroccan workshop.",
      "credit": "Photo by Moussa Idrissi on Pexels",
      "query": "wood carving artisan hands chisel"
    },
    {
      "url": "https://images.pexels.com/photos/26792961/pexels-photo-26792961.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "A skilled artisan crafting a detailed bronze deity statue in Kumbakonam, India.",
      "credit": "Photo by Alwin Suhas on Pexels",
      "query": "brass idol statue indian traditional"
    },
    {
      "url": "https://images.pexels.com/photos/11453882/pexels-photo-11453882.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Detailed hand-carved Buddha head statue placed beside a traditional wooden door, showcasing artistry and spirituality.",
      "credit": "Photo by Mehmet Turgut  Kirkgoz on Pexels",
      "query": "sandalwood carved figurine detail"
    }
  ],
  "mysuru": [
    {
      "url": "https://images.pexels.com/photos/14702568/pexels-photo-14702568.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Detail of Mysore Palace showcasing traditional oriental architecture in India.",
      "credit": "Photo by Keith Lobo on Pexels",
      "query": "mysore palace karnataka india"
    },
    {
      "url": "https://images.pexels.com/photos/8751537/pexels-photo-8751537.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Intricate henna design being applied on a woman's hand at a cultural ceremony.",
      "credit": "Photo by Anastasia  Shuraeva on Pexels",
      "query": "indian traditional painting gold leaf"
    },
    {
      "url": "https://images.pexels.com/photos/27951051/pexels-photo-27951051.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "Piles of red-tipped incense sticks on a concrete floor, ready for packaging.",
      "credit": "Photo by HONG SON on Pexels",
      "query": "sandalwood incense sticks india"
    },
    {
      "url": "https://images.pexels.com/photos/33395641/pexels-photo-33395641.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "alt": "An intricately designed wooden box placed on lush green foliage, creating a beautiful contrast.",
      "credit": "Photo by Tahir Xəlfəquliyev on Pexels",
      "query": "indian wooden inlay box craft"
    }
  ]
}
