// GENERATED by scripts/resolve-product-images.mjs — do not edit.
//
// One representative photo per (category, occasion), taken from the same
// resolver run that produced the product image_url values. Importing from
// here keeps the landing page in step with the shop; the previous
// hand-maintained copy in imagery.js had silently gone stale.

export const GENERATED_CATALOGUE_PHOTOS = {
  "Gifts": {
    "Diwali": "https://images.pexels.com/photos/8819781/pexels-photo-8819781.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  },
  "Hampers": {
    "Chocolate": "https://images.pexels.com/photos/20699854/pexels-photo-20699854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Baby Shower": "https://images.pexels.com/photos/20699855/pexels-photo-20699855.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Birthday": "https://images.pexels.com/photos/13975271/pexels-photo-13975271.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Corporate": "https://images.pexels.com/photos/10182772/pexels-photo-10182772.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Diwali": "https://images.pexels.com/photos/3135229/pexels-photo-3135229.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Housewarming": "https://images.pexels.com/photos/36813411/pexels-photo-36813411.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Rakhi": "https://images.pexels.com/photos/7685636/pexels-photo-7685636.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Get Well": "https://images.pexels.com/photos/10720839/pexels-photo-10720839.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Anniversary": "https://images.pexels.com/photos/37606032/pexels-photo-37606032.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  },
  "Party Essentials": {
    "Baby Shower": "https://images.pexels.com/photos/12114825/pexels-photo-12114825.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Balloon Decor": "https://images.pexels.com/photos/7336918/pexels-photo-7336918.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Default": "https://images.pexels.com/photos/28173091/pexels-photo-28173091.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Birthday": "https://images.pexels.com/photos/7180255/pexels-photo-7180255.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Wedding & Engagement": "https://images.pexels.com/photos/2449445/pexels-photo-2449445.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Tableware": "https://images.pexels.com/photos/37042839/pexels-photo-37042839.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Backdrop & Banners": "https://images.pexels.com/photos/38786129/pexels-photo-38786129.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Theme Party": "https://images.pexels.com/photos/25559074/pexels-photo-25559074.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Farewell": "https://images.pexels.com/photos/8127310/pexels-photo-8127310.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Housewarming": "https://images.pexels.com/photos/37815970/pexels-photo-37815970.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Independence Day": "https://images.pexels.com/photos/8805994/pexels-photo-8805994.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Anniversary": "https://images.pexels.com/photos/10336805/pexels-photo-10336805.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  },
  "Pooja & Essentials": {
    "Default": "https://images.pexels.com/photos/7351728/pexels-photo-7351728.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Griha Pravesh": "https://images.pexels.com/photos/37531057/pexels-photo-37531057.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Small Functions": "https://images.pexels.com/photos/35171273/pexels-photo-35171273.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Satyanarayan Pooja": "https://images.pexels.com/photos/36608903/pexels-photo-36608903.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Daily Pooja": "https://images.pexels.com/photos/37116936/pexels-photo-37116936.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Diwali": "https://images.pexels.com/photos/11092914/pexels-photo-11092914.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Navratri": "https://images.pexels.com/photos/29370139/pexels-photo-29370139.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Ganesh Chaturthi": "https://images.pexels.com/photos/18658452/pexels-photo-18658452.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Wedding Pooja": "https://images.pexels.com/photos/31002035/pexels-photo-31002035.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Janmashtami": "https://images.pexels.com/photos/29359312/pexels-photo-29359312.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "Regional & Other": "https://images.pexels.com/photos/8887006/pexels-photo-8887006.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  }
}

export const GENERATED_CATEGORY_PHOTO = Object.fromEntries(
  Object.entries(GENERATED_CATALOGUE_PHOTOS).map(([category, byOccasion]) => [
    category,
    Object.values(byOccasion)[0] ?? null,
  ])
)
