// GENERATED by scripts/resolve-product-images.mjs — do not edit by hand.
//
// This file is committed empty and stays empty until someone runs a full
// resolver pass:
//
//     node scripts/resolve-product-images.mjs
//
// That run writes the per-product SQL (migration 024) and overwrites this
// module in the same pass, from the same data. imagery.js layers whatever
// is here on top of its hardcoded fallbacks, so:
//
//   • empty  → the landing page behaves exactly as it did before,
//   • filled → the landing page and the shop are guaranteed to agree.
//
// The point is the guarantee. The previous arrangement had migration 017's
// URLs copied by hand into imagery.js, and the copy had already gone stale:
// it still declares Party Essentials and Pooja & Essentials as having no
// photo, which stopped being true when migration 021 filled both in the
// database. A card on the landing page could therefore show one thing and
// the product it linked to show another — the same class of mismatch this
// whole feature exists to remove, one level up.

export const GENERATED_CATALOGUE_PHOTOS = {}

export const GENERATED_CATEGORY_PHOTO = {}
