// GENERATED by scripts/generate-cake-catalog.mjs — do not edit.
//
// One representative photograph per cake occasion, taken from the same
// resolver run that assigned the product photos in migration 029 (plus the
// cakes that were already in the catalogue). The occasion rail on the cake
// shop reads from here, so it cannot drift away from the products it links
// to — which is exactly what happened to the hand-maintained imagery.js.
//
// These are licensed stock photographs of similar cakes, not photographs of
// a Sambramo deliverable. See migration 023 on image_source.

export const CAKE_OCCASION_PHOTOS = {
  "Annaprashan": "https://images.pexels.com/photos/8887050/pexels-photo-8887050.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Anniversary": "https://images.pexels.com/photos/11112058/pexels-photo-11112058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Baby Shower": "https://images.pexels.com/photos/6461823/pexels-photo-6461823.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Birthday": "https://images.pexels.com/photos/10949653/pexels-photo-10949653.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Bride to Be": "https://images.pexels.com/photos/1829423/pexels-photo-1829423.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Christmas": "https://images.pexels.com/photos/14524823/pexels-photo-14524823.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Congratulations": "https://images.pexels.com/photos/7723809/pexels-photo-7723809.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Corporate": "https://images.pexels.com/photos/16140003/pexels-photo-16140003.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Diwali": "https://images.pexels.com/photos/30604307/pexels-photo-30604307.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Eggless": "https://images.pexels.com/photos/2147868/pexels-photo-2147868.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Eid": "https://images.pexels.com/photos/35829604/pexels-photo-35829604.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Engagement": "https://images.pexels.com/photos/6258052/pexels-photo-6258052.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Farewell": "https://images.pexels.com/photos/12927170/pexels-photo-12927170.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Father's Day": "https://images.pexels.com/photos/2004162/pexels-photo-2004162.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "First Birthday": "https://images.pexels.com/photos/961192/pexels-photo-961192.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "First Day at School": "https://images.pexels.com/photos/28503353/pexels-photo-28503353.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Friendship Day": "https://images.pexels.com/photos/7254232/pexels-photo-7254232.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Ganesh Chaturthi": "https://images.pexels.com/photos/33643272/pexels-photo-33643272.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Gender Reveal": "https://images.pexels.com/photos/6461824/pexels-photo-6461824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Get Well Soon": "https://images.pexels.com/photos/7552332/pexels-photo-7552332.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Gluten-Free": "https://images.pexels.com/photos/18232621/pexels-photo-18232621.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Groom to Be": "https://images.pexels.com/photos/14396233/pexels-photo-14396233.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Haldi & Mehendi": "https://images.pexels.com/photos/33078524/pexels-photo-33078524.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Half Birthday": "https://images.pexels.com/photos/34636546/pexels-photo-34636546.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Holi": "https://images.pexels.com/photos/8887061/pexels-photo-8887061.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Housewarming": "https://images.pexels.com/photos/35241181/pexels-photo-35241181.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Independence Day": "https://images.pexels.com/photos/10513305/pexels-photo-10513305.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Just Because": "https://images.pexels.com/photos/35567498/pexels-photo-35567498.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Kids & Theme": "https://images.pexels.com/photos/1857157/pexels-photo-1857157.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Milestone Birthday": "https://images.pexels.com/photos/12689012/pexels-photo-12689012.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Mother's Day": "https://images.pexels.com/photos/16369857/pexels-photo-16369857.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Mundan": "https://images.pexels.com/photos/7096659/pexels-photo-7096659.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Naming Ceremony": "https://images.pexels.com/photos/3593428/pexels-photo-3593428.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Navratri": "https://images.pexels.com/photos/17264037/pexels-photo-17264037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "New Beginnings": "https://images.pexels.com/photos/32370608/pexels-photo-32370608.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "New Year": "https://images.pexels.com/photos/6024650/pexels-photo-6024650.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Pet Birthday": "https://images.pexels.com/photos/37330441/pexels-photo-37330441.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Photo Cake": "https://images.pexels.com/photos/36568408/pexels-photo-36568408.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Pongal & Onam": "https://images.pexels.com/photos/35763760/pexels-photo-35763760.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Proposal": "https://images.pexels.com/photos/28657134/pexels-photo-28657134.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Rakhi": "https://images.pexels.com/photos/18231728/pexels-photo-18231728.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Retirement": "https://images.pexels.com/photos/30877722/pexels-photo-30877722.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Roka": "https://images.pexels.com/photos/8819771/pexels-photo-8819771.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Sangeet": "https://images.pexels.com/photos/11094777/pexels-photo-11094777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Sorry": "https://images.pexels.com/photos/7333063/pexels-photo-7333063.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Sugar-Free": "https://images.pexels.com/photos/1359334/pexels-photo-1359334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Teachers Day": "https://images.pexels.com/photos/12526538/pexels-photo-12526538.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Thank You": "https://images.pexels.com/photos/1098556/pexels-photo-1098556.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Valentine": "https://images.pexels.com/photos/31629972/pexels-photo-31629972.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Vegan": "https://images.pexels.com/photos/36203728/pexels-photo-36203728.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "Wedding": "https://images.pexels.com/photos/38598633/pexels-photo-38598633.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
}
