// GENERATED by scripts/resolve-decor-samples.mjs — do not edit.
//
// One distinct photograph per decoration sample, keyed `eventId/sampleId` to
// match the entries in decorSamples.js. Every URL here is a licensed stock
// photograph of a similar setup, never a photograph of work Sambramo has
// delivered — see the header of decorSamples.js for why that distinction is
// load-bearing rather than pedantic.
//
// Re-run the resolver rather than editing this file:
//   node scripts/resolve-decor-samples.mjs --dry-run
//   node scripts/resolve-decor-samples.mjs
//
// Resolved 2026-08-10 from pexels. 60 setups.

export const GENERATED_DECOR_PHOTOS = {
  "anniversary/candle-dinner": {
    url:    "https://images.pexels.com/photos/29616297/pexels-photo-29616297.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Couple enjoying a romantic dinner with rose petals and candlelight, creating a perfect evening setting.",
    credit: "Photo by Nadin Sh on Pexels",
    source: "stock",
  },
  "anniversary/floral-stage": {
    url:    "https://images.pexels.com/photos/13434448/pexels-photo-13434448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Bride and groom kissing while cutting a wedding cake surrounded by flowers.",
    credit: "Photo by Jonathan Nenemann on Pexels",
    source: "stock",
  },
  "anniversary/milestone": {
    url:    "https://images.pexels.com/photos/14646769/pexels-photo-14646769.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A luxurious dining table setup featuring crystal glasses, elegant plates, and golden decor for a sophisticated ambiance.",
    credit: "Photo by Vidal Balielo Jr. on Pexels",
    source: "stock",
  },
  "anniversary/room-surprise": {
    url:    "https://images.pexels.com/photos/16470652/pexels-photo-16470652.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Elegant hotel room decorated with balloons and a 'Happy Birthday' banner, creating a festive atmosphere.",
    credit: "Photo by Guy Joben on Pexels",
    source: "stock",
  },
  "baby_shower/floral-swing": {
    url:    "https://images.pexels.com/photos/32573161/pexels-photo-32573161.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Sophisticated baby shower setup featuring a floral arch with gold 'Welcome Baby' sign and elegant table settings.",
    credit: "Photo by MAG Photography on Pexels",
    source: "stock",
  },
  "baby_shower/godh-bharai": {
    url:    "https://images.pexels.com/photos/35591621/pexels-photo-35591621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant flower arrangement with marigolds and rose petals on a ceremonial table.",
    credit: "Photo by Deepak Sharma on Pexels",
    source: "stock",
  },
  "baby_shower/pastel-arch": {
    url:    "https://images.pexels.com/photos/12114820/pexels-photo-12114820.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Soft and inviting baby shower setup featuring beige teddy bears and balloon decor.",
    credit: "Photo by Jonathan Nenemann on Pexels",
    source: "stock",
  },
  "baby_shower/reveal": {
    url:    "https://images.pexels.com/photos/6463611/pexels-photo-6463611.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Excited friends celebrate a gender reveal with balloons and confetti indoors.",
    credit: "Photo by Tima Miroshnichenko on Pexels",
    source: "stock",
  },
  "birthday/balloon-arch": {
    url:    "https://images.pexels.com/photos/11282245/pexels-photo-11282245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A beautifully decorated pink themed birthday party with floral arrangements and balloon arches.",
    credit: "Photo by Vidal Balielo Jr. on Pexels",
    source: "stock",
  },
  "birthday/dessert-table": {
    url:    "https://images.pexels.com/photos/27175437/pexels-photo-27175437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant dessert table with cupcakes and toy car at a birthday party.",
    credit: "Photo by Helena Lopes on Pexels",
    source: "stock",
  },
  "birthday/full-party": {
    url:    "https://images.pexels.com/photos/12688989/pexels-photo-12688989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Interior of an upscale event venue with decorative lighting and empty seating area, perfect for weddings or parties.",
    credit: "Photo by Vidal Balielo Jr. on Pexels",
    source: "stock",
  },
  "birthday/theme-room": {
    url:    "https://images.pexels.com/photos/16475253/pexels-photo-16475253.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant dinosaur-themed birthday party decorations on a table setup for kids",
    credit: "Photo by Luis Quintero on Pexels",
    source: "stock",
  },
  "corporate_event/av": {
    url:    "https://images.pexels.com/photos/8761299/pexels-photo-8761299.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "An empty conference room with chairs, a projector screen, and presentation setup.",
    credit: "Photo by Pavel Danilyuk on Pexels",
    source: "stock",
  },
  "corporate_event/full-corporate": {
    url:    "https://images.pexels.com/photos/9275222/pexels-photo-9275222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Audience attentively watching a presentation in a conference setting, with stage lights and speaker visible.",
    credit: "Photo by Atlantic Ambience on Pexels",
    source: "stock",
  },
  "corporate_event/registration": {
    url:    "https://images.pexels.com/photos/7648051/pexels-photo-7648051.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Two women arranging name badges at a registration desk during a corporate event.",
    credit: "Photo by RDNE Stock project on Pexels",
    source: "stock",
  },
  "corporate_event/stage-branding": {
    url:    "https://images.pexels.com/photos/16856359/pexels-photo-16856359.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Two men in blue suits pose at a professional conference against a branded backdrop.",
    credit: "Photo by Domingos Henriques on Pexels",
    source: "stock",
  },
  "engagement/entrance-photo": {
    url:    "https://images.pexels.com/photos/26623743/pexels-photo-26623743.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Stylish engagement party decor with neon sign, flowers, and elegant seating indoors.",
    credit: "Photo by Taha Samet Arslan on Pexels",
    source: "stock",
  },
  "engagement/full-engagement": {
    url:    "https://images.pexels.com/photos/14646741/pexels-photo-14646741.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Elegant interior of a luxurious empty banquet hall with vibrant stage lighting and exquisite table settings.",
    credit: "Photo by Vidal Balielo Jr. on Pexels",
    source: "stock",
  },
  "engagement/intimate": {
    url:    "https://images.pexels.com/photos/30417806/pexels-photo-30417806.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Cozy atmosphere with candles and rose petals creating a romantic ambiance.",
    credit: "Photo by Megwara Favour on Pexels",
    source: "stock",
  },
  "engagement/ring-stage": {
    url:    "https://images.pexels.com/photos/30215316/pexels-photo-30215316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A couple in traditional attire sit on a floral stage during an Indian wedding ceremony, surrounded by colorful decorations.",
    credit: "Photo by Fotographiya Wedding Photography on Pexels",
    source: "stock",
  },
  "first_birthday/floral-soft": {
    url:    "https://images.pexels.com/photos/34292277/pexels-photo-34292277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Adorable baby boy celebrating first birthday with floral decorations indoors.",
    credit: "Photo by Krishna Kids  Photography on Pexels",
    source: "stock",
  },
  "first_birthday/grand-first": {
    url:    "https://images.pexels.com/photos/12432504/pexels-photo-12432504.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Luxurious wedding hall with elegant decor, chairs with red ribbons, and illuminated stage.",
    credit: "Photo by BANU FILM  ADS on Pexels",
    source: "stock",
  },
  "first_birthday/one-backdrop": {
    url:    "https://images.pexels.com/photos/8097575/pexels-photo-8097575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Festive first birthday photo setup with balloons, blocks, and a wooden number one.",
    credit: "Photo by Melike  B on Pexels",
    source: "stock",
  },
  "first_birthday/play-corner": {
    url:    "https://images.pexels.com/photos/27175469/pexels-photo-27175469.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A child sits happily in a vibrant ball pit at an indoor play area.",
    credit: "Photo by Helena Lopes on Pexels",
    source: "stock",
  },
  "get_together/full-party": {
    url:    "https://images.pexels.com/photos/37958130/pexels-photo-37958130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Charming outdoor evening event setup with string lights, red tablecloths, and wooden chairs under a canopy.",
    credit: "Photo by Jonathan Borba on Pexels",
    source: "stock",
  },
  "get_together/lounge": {
    url:    "https://images.pexels.com/photos/17023004/pexels-photo-17023004.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Beautifully decorated outdoor lounge area with sofa, glass tables, and plants.",
    credit: "Photo by Matheus Bertelli on Pexels",
    source: "stock",
  },
  "get_together/reunion-wall": {
    url:    "https://images.pexels.com/photos/15928649/pexels-photo-15928649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Outdoor display of photographs hanging from strings on a tree in a garden setting.",
    credit: "Photo by Pew Nguyen on Pexels",
    source: "stock",
  },
  "get_together/terrace": {
    url:    "https://images.pexels.com/photos/37721064/pexels-photo-37721064.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Elegant outdoor patio with string lights and chairs, perfect for evening gatherings.",
    credit: "Photo by Daniel Agundiz on Pexels",
    source: "stock",
  },
  "graduation/balloon-cap": {
    url:    "https://images.pexels.com/photos/7944178/pexels-photo-7944178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Graduates celebrate indoors with confetti and balloons, capturing joyful post-ceremony moments.",
    credit: "Photo by Pavel Danilyuk on Pexels",
    source: "stock",
  },
  "graduation/full-grad": {
    url:    "https://images.pexels.com/photos/7942491/pexels-photo-7942491.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Graduates celebrate in an indoor gymnasium with friends and family during a graduation ceremony.",
    credit: "Photo by Pavel Danilyuk on Pexels",
    source: "stock",
  },
  "graduation/memory-board": {
    url:    "https://images.pexels.com/photos/4780860/pexels-photo-4780860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Black and white vintage photos pinned against a corkboard with colorful clothespins.",
    credit: "Photo by julia lee on Pexels",
    source: "stock",
  },
  "graduation/photo-corner": {
    url:    "https://images.pexels.com/photos/31742586/pexels-photo-31742586.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Family posing together for a graduation photo with a backdrop of bookshelves.",
    credit: "Photo by VIOLA STUDIO PHOTO on Pexels",
    source: "stock",
  },
  "housewarming/entrance": {
    url:    "https://images.pexels.com/photos/8887264/pexels-photo-8887264.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Colorful floral garlands being arranged for a festive ceremony at a wooden doorway.",
    credit: "Photo by Lara Jameson on Pexels",
    source: "stock",
  },
  "housewarming/full-griha": {
    url:    "https://images.pexels.com/photos/12432079/pexels-photo-12432079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A vibrant Indian ceremony with a decorated plate of flowers and lit diya, symbolizing tradition.",
    credit: "Photo by BANU FILM  ADS on Pexels",
    source: "stock",
  },
  "housewarming/pooja-mandap": {
    url:    "https://images.pexels.com/photos/37116935/pexels-photo-37116935.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A colorful Ganesha puja setup indoors with flowers, fruits, and traditional items, symbolizing Indian culture and spirituality.",
    credit: "Photo by Vijay Krishnawat on Pexels",
    source: "stock",
  },
  "housewarming/welcome-decor": {
    url:    "https://images.pexels.com/photos/8293688/pexels-photo-8293688.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A cheerful couple stands at their new home entrance holding a welcome sign.",
    credit: "Photo by RDNE Stock project on Pexels",
    source: "stock",
  },
  "naming_ceremony/cradle": {
    url:    "https://images.pexels.com/photos/35094073/pexels-photo-35094073.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant balloons and 'Naming Ceremony' sign against a red backdrop, perfect for celebration-themed events.",
    credit: "Photo by Ashish Keshkar on Pexels",
    source: "stock",
  },
  "naming_ceremony/full-naming": {
    url:    "https://images.pexels.com/photos/38506966/pexels-photo-38506966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Smiling baby in white knitted outfit rests in a cozy cradle surrounded by flowers and pine cones.",
    credit: "Photo by Krishna Kids  Photography on Pexels",
    source: "stock",
  },
  "naming_ceremony/homam": {
    url:    "https://images.pexels.com/photos/13405691/pexels-photo-13405691.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A Hindu priest performing a sacred fire ritual inside a dimly lit room, highlighting spiritual traditions.",
    credit: "Photo by Teja J on Pexels",
    source: "stock",
  },
  "naming_ceremony/name-board": {
    url:    "https://images.pexels.com/photos/38720256/pexels-photo-38720256.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant family celebration for a baby's weaning ceremony, featuring traditional attire and joyful decorations indoors.",
    credit: "Photo by Photographer Gyanu on Pexels",
    source: "stock",
  },
  "retirement/dining-decor": {
    url:    "https://images.pexels.com/photos/2922313/pexels-photo-2922313.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Elegant table setting with wine glasses and decor in softened light, perfect for formal dining or weddings.",
    credit: "Photo by Rene Terp on Pexels",
    source: "stock",
  },
  "retirement/full-retirement": {
    url:    "https://images.pexels.com/photos/7810933/pexels-photo-7810933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Happy seniors celebrating indoors with balloons and laughter. Perfect for festive and joyful lifestyle themes.",
    credit: "Photo by Kampus Production on Pexels",
    source: "stock",
  },
  "retirement/memory-wall": {
    url:    "https://images.pexels.com/photos/296649/pexels-photo-296649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Collection of vintage Polaroid photos clipped to a wooden wall indoors.",
    credit: "Photo by Vladyslav Dukhin on Pexels",
    source: "stock",
  },
  "retirement/stage-felicitation": {
    url:    "https://images.pexels.com/photos/32008345/pexels-photo-32008345.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Empty wooden stage with traditional flags and red carpet in a vintage hall, creating a classic and formal ambiance.",
    credit: "Photo by Guohua Song on Pexels",
    source: "stock",
  },
  "sangeet/boho-backdrop": {
    url:    "https://images.pexels.com/photos/36652869/pexels-photo-36652869.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Bright orange and yellow marigold garlands hanging against a clear sky, symbolizing celebration.",
    credit: "Photo by The Visionary Vows on Pexels",
    source: "stock",
  },
  "sangeet/dance-floor": {
    url:    "https://images.pexels.com/photos/38656749/pexels-photo-38656749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A groom joyfully celebrates during a vibrant night wedding with colorful decorations and festive lighting.",
    credit: "Photo by Solon Das on Pexels",
    source: "stock",
  },
  "sangeet/full-sangeet": {
    url:    "https://images.pexels.com/photos/27443997/pexels-photo-27443997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A couple gracefully dances during a nighttime Indian wedding, adorned in traditional attire.",
    credit: "Photo by Sabir Khan Shourov on Pexels",
    source: "stock",
  },
  "sangeet/mehendi-corner": {
    url:    "https://images.pexels.com/photos/12343967/pexels-photo-12343967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Colorful mehendi ceremony setup with smoke effects, featuring yellow and red decor in an outdoor garden setting.",
    credit: "Photo by santosh bhagat on Pexels",
    source: "stock",
  },
  "seemantham/bangle-corner": {
    url:    "https://images.pexels.com/photos/38773213/pexels-photo-38773213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Close-up of traditional Maharashtrian wedding rituals with mehendi and bangles.",
    credit: "Photo by Satyam vicky on Pexels",
    source: "stock",
  },
  "seemantham/flower-seat": {
    url:    "https://images.pexels.com/photos/27060269/pexels-photo-27060269.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A close-up of coconuts decorated with flowers used in a traditional Indian wedding ceremony.",
    credit: "Photo by BANU FILM  ADS on Pexels",
    source: "stock",
  },
  "seemantham/full-seemantham": {
    url:    "https://images.pexels.com/photos/14395559/pexels-photo-14395559.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant Indian wedding stage setup with colorful flower garlands and golden columns.",
    credit: "Photo by BANU FILM  ADS on Pexels",
    source: "stock",
  },
  "seemantham/ritual-setup": {
    url:    "https://images.pexels.com/photos/7685991/pexels-photo-7685991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Vibrant Indian celebration featuring hands holding a traditional puja thali with a candle flame.",
    credit: "Photo by RDNE Stock project on Pexels",
    source: "stock",
  },
  "thread_ceremony/floral-entrance": {
    url:    "https://images.pexels.com/photos/34056580/pexels-photo-34056580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Stylish Hindu ceremony setup with ornate backdrop, symbolic decor, and vibrant textiles indoors.",
    credit: "Photo by ViAn Photography on Pexels",
    source: "stock",
  },
  "thread_ceremony/full-upanayanam": {
    url:    "https://images.pexels.com/photos/7458680/pexels-photo-7458680.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Close-up of a traditional Tamil ceremony with vibrant yellow flowers and oil lamps, showcasing cultural rituals.",
    credit: "Photo by Suren Ram on Pexels",
    source: "stock",
  },
  "thread_ceremony/ritual-space": {
    url:    "https://images.pexels.com/photos/38928329/pexels-photo-38928329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A black and white photo capturing the sacred Upanayanam ceremony outdoors in India.",
    credit: "Photo by sunaina ravikumar on Pexels",
    source: "stock",
  },
  "thread_ceremony/seating": {
    url:    "https://images.pexels.com/photos/34357888/pexels-photo-34357888.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Rows of stylish woven chairs arranged for an outdoor wedding ceremony under a tent.",
    credit: "Photo by Jonathan Borba on Pexels",
    source: "stock",
  },
  "wedding/entrance": {
    url:    "https://images.pexels.com/photos/34541356/pexels-photo-34541356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "A rustic stone wall with a wooden gate adorned by vibrant pink bougainvillea flowers, creating a picturesque entrance.",
    credit: "Photo by Murat Halıcı on Pexels",
    source: "stock",
  },
  "wedding/full-wedding": {
    url:    "https://images.pexels.com/photos/17931466/pexels-photo-17931466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Luxurious indoor wedding venue featuring a floral-adorned grand staircase and elegant table settings.",
    credit: "Photo by Juliano Astc on Pexels",
    source: "stock",
  },
  "wedding/mandap": {
    url:    "https://images.pexels.com/photos/34079355/pexels-photo-34079355.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Luxurious floral wedding mandap decorated with chandeliers, perfect for elegant indoor ceremonies.",
    credit: "Photo by The Visionary Vows on Pexels",
    source: "stock",
  },
  "wedding/reception-stage": {
    url:    "https://images.pexels.com/photos/32142657/pexels-photo-32142657.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    alt:    "Happy couple posing at elegant wedding reception with beautiful floral decorations and lighting.",
    credit: "Photo by Luis Morales Torres on Pexels",
    source: "stock",
  },
}
