// GENERATED by scripts/refresh-market-rates.mjs — do not edit.
//
// Committed with `asOf: null`, which is the deliberate starting state: every
// multiplier resolves to 1.00 and the app prices at its published baseline.
// See data/marketRates.js for why a missing index degrades to the baseline
// rather than to zero, and what is and is not actually tracked.
//
// To make it live:
//   1. get a free API key at https://data.gov.in (register → My Account → API)
//   2. put DATA_GOV_IN_API_KEY=<key> in .env
//   3. node scripts/refresh-market-rates.mjs --dry-run
//   4. node scripts/refresh-market-rates.mjs
//
// Then run it on a schedule. Daily is right; the mandi data is published
// daily and data/marketRates.js treats anything older than ten days as stale
// and reverts to the baseline on its own.

export const GENERATED_MARKET_INDEX = {
  /** ISO date of the read. `null` means "never run" — the baseline applies. */
  asOf: null,

  /** Multiplier per cost component, against the committed rates. */
  multipliers: {
    provisions: 1,
    kitchen: 1,
    service: 1,
    decor: 1,
  },

  /**
   * What the provisions multiplier was computed from, for the panel that
   * shows a customer where the number came from. Each entry is
   * `{ commodity, unit, modal, baseline, weight }`.
   */
  basket: [],
}
