import { useEffect, useState } from 'react'
import { Download, X } from 'lucide-react'
import { isNativeApp } from '../../lib/nativePush'

/**
 * "There is a newer version."
 *
 * ══════════════════════════════════════════════════════════════════════
 * WHY AN INSTALLED APP NEEDS TELLING AT ALL
 * ══════════════════════════════════════════════════════════════════════
 *
 * The web app updates itself: a deploy lands and the next load has it.
 * The APK does not. Its code is compiled in, which is the whole reason
 * it works — the bridge injects, push registers, no service worker can
 * serve yesterday's bundle. The cost of that is a phone that stays on
 * whatever was installed until somebody replaces it by hand.
 *
 * Until the apps are on the Play Store there is no updater to do it, so
 * the app has to say so itself. A partner sitting on a build with a
 * broken booking screen has no way of knowing a fixed one exists.
 *
 * ══════════════════════════════════════════════════════════════════════
 * IT MUST COMPARE APK TO APK
 * ══════════════════════════════════════════════════════════════════════
 *
 * The first version compared the APK's stamped build against the
 * WEBSITE's build, and told every user to update, forever, on the
 * newest APK there was.
 *
 * Those two are legitimately different and always will be. The site
 * deploys on every push; the APK rebuilds only when something under
 * src/ changes. Two current builds, two different shas — so "they
 * differ" answers a question nobody asked.
 *
 * The right comparison is against the newest APK, and the honest place
 * to publish that is the release the APK itself comes from. The Android
 * workflow uploads `version.json` beside the two .apk files, so the
 * value can only ever describe a build that actually exists.
 *
 * ── Failing safe ────────────────────────────────────────────────────
 * Anything unclear — a failed fetch, a missing file, 'dev', a value
 * equal to ours — shows nothing. A false "update available" is worse
 * than a missed one: it teaches people to dismiss the prompt, and the
 * time it matters is the time they will.
 *
 * ── Why not a version number ────────────────────────────────────────
 * A number has to be bumped, and the one time somebody forgets is the
 * release where it mattered. The commit sha is generated by the act of
 * building and cannot drift from what was built.
 *
 * ══════════════════════════════════════════════════════════════════════
 * IT NEVER BLOCKS
 * ══════════════════════════════════════════════════════════════════════
 *
 * Dismissable, and it stays dismissed for that build. A master mid-way
 * through accepting a 45-second offer must not be handed a modal, and
 * an update prompt that reappears every launch is the `nagging` pattern
 * in config/legal.js.
 *
 * The web is unaffected — it updates on its own, so this renders
 * nothing there.
 */

const BUILD = (import.meta.env?.VITE_BUILD ?? 'dev').slice(0, 7)
const DISMISS_KEY = 'sambramo_update_dismissed'

/* Published beside the APKs, in the release they come from — so it
   cannot describe a build that was never packaged. A release asset is a
   plain CDN URL with no API rate limit, unlike the GitHub API. */
const VERSION_URL =
  'https://github.com/mohankumars11/EventsEase_start/releases/download/android-latest/version.json'

export default function UpdateAvailable({ app = 'customer' }) {
  const [latest, setLatest] = useState(null)
  const [gone, setGone] = useState(false)

  useEffect(() => {
    // Only the installed app can be out of date.
    if (!isNativeApp() || BUILD === 'dev') return

    let dead = false
    ;(async () => {
      try {
        // `no-store`, or the WebView will happily serve the copy it
        // fetched on the launch that told it it was up to date.
        const res = await fetch(VERSION_URL, { cache: 'no-store' })
        if (!res.ok) return
        const body = await res.json()
        if (dead) return

        const live = String(body.build ?? '').slice(0, 7)

        /* Every uncertain case is silence.
         *
         * No value, our own value, or a placeholder from a build that
         * did not stamp itself — none of those is evidence that a newer
         * APK exists, and only evidence should produce a prompt. */
        if (!live || live === 'dev' || live === BUILD) return

        try {
          if (localStorage.getItem(DISMISS_KEY) === live) return
        } catch { /* storage off */ }

        setLatest(live)
      } catch {
        /* Offline, or the site is down. Neither is worth a message: the
           app works, and "could not check for updates" is a sentence
           nobody has ever been glad to read. */
      }
    })()

    return () => { dead = true }
  }, [])

  if (!latest || gone) return null

  const apk = `https://github.com/mohankumars11/EventsEase_start/releases/download/android-latest/sambramo-${app}.apk`

  function dismiss() {
    setGone(true)
    // Keyed to the version, so the NEXT update asks again.
    try { localStorage.setItem(DISMISS_KEY, latest) } catch { /* storage off */ }
  }

  return (
    <div className="fixed inset-x-3 bottom-3 z-[140] rounded-[22px] bg-plum-950 p-4 text-white shadow-[0_10px_40px_-12px_rgba(0,0,0,.5)]">
      <button
        onClick={dismiss}
        aria-label="Not now"
        className="absolute right-2.5 top-2.5 rounded-full p-1.5 text-white/50 hover:bg-white/10"
      >
        <X size={15} />
      </button>

      <p className="pr-6 text-[14.5px] font-extrabold leading-tight">
        A newer version is ready
      </p>
      <p className="mt-1.5 text-[12.5px] leading-relaxed text-white/75">
        You are on build {BUILD}. Installing over the top keeps you signed in
        and keeps your jobs.
      </p>

      <a
        href={apk}
        className="mt-3 flex items-center justify-center gap-2 rounded-2xl bg-saffron-400 py-3 text-[14px] font-extrabold text-plum-950"
      >
        <Download size={16} /> Update now
      </a>

      <button onClick={dismiss} className="mt-1.5 w-full py-1.5 text-[12px] font-bold text-white/55">
        Not now
      </button>
    </div>
  )
}
