-- ============================================================
-- Migration 015: Real product catalog expansion — 300+ items
-- across all Shop categories, each tagged with an "occasion" so
-- a category can be filtered by event (e.g. Gifts -> Birthday /
-- Wedding / Rakhi / Diwali / ...), not shown as one flat list.
-- Run this ONCE in: Supabase Dashboard → SQL Editor
-- (products.id has no unique constraint beyond the UUID primary
-- key, so re-running this file will insert duplicates.)
-- ============================================================

ALTER TABLE products ADD COLUMN IF NOT EXISTS occasion TEXT;
CREATE INDEX IF NOT EXISTS idx_products_category_occasion ON products(category, occasion);


-- Cakes (51 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Vanilla Sponge Birthday Cake (1kg)', 'Cakes', 'Birthday', 'Classic vanilla sponge, buttercream frosting', 749, '🎂'),
  ('Chocolate Overload Birthday Cake (1kg)', 'Cakes', 'Birthday', 'Layers of dark chocolate ganache', 899, '🍫'),
  ('Rainbow Layer Cake (1kg)', 'Cakes', 'Birthday', 'Six vibrant sponge layers, vanilla cream', 999, '🌈'),
  ('Number Shaped Cake (0.5kg)', 'Cakes', 'Birthday', 'Cake baked in your age number''s shape', 899, '🔢'),
  ('Barbie Theme Cake (1.5kg)', 'Cakes', 'Birthday', 'Pink fondant, doll topper', 1799, '👗'),
  ('Cartoon Theme Cake (1kg)', 'Cakes', 'Birthday', 'Kids'' favourite cartoon character fondant', 1499, '🎨'),
  ('Black Forest Birthday Cake (1kg)', 'Cakes', 'Birthday', 'Cherries, whipped cream, chocolate shavings', 849, '🍒'),
  ('Fondant Birthday Cake (1kg)', 'Cakes', 'Birthday', 'Smooth fondant finish, custom message', 1299, '🎨'),
  ('Three-Tier Wedding Cake (3kg)', 'Cakes', 'Wedding', 'Classic tiered cake, serves 40', 4999, '💍'),
  ('White Fondant Wedding Cake (2kg)', 'Cakes', 'Wedding', 'Elegant white fondant with sugar flowers', 3499, '🤍'),
  ('Red Velvet Wedding Cake (2kg)', 'Cakes', 'Wedding', 'Rich red velvet, cream cheese frosting', 2999, '❤️'),
  ('Floral Wedding Cake (2kg)', 'Cakes', 'Wedding', 'Buttercream florals, pastel palette', 3299, '🌸'),
  ('Naked Wedding Cake (1.5kg)', 'Cakes', 'Wedding', 'Semi-frosted rustic style', 2799, '🌿'),
  ('Chocolate Ganache Wedding Cake (2kg)', 'Cakes', 'Wedding', 'Dark ganache drip cake', 3199, '🍫'),
  ('Heart-Shaped Anniversary Cake (1kg)', 'Cakes', 'Anniversary', 'Red velvet in a heart mould', 999, '💕'),
  ('Golden Anniversary Cake (1kg)', 'Cakes', 'Anniversary', 'Gold leaf finish, elegant', 1399, '✨'),
  ('Silver Jubilee Cake (1kg)', 'Cakes', 'Anniversary', '25th anniversary special, silver accents', 1299, '🥈'),
  ('Couple Photo Cake (1kg)', 'Cakes', 'Anniversary', 'Edible print of your couple photo', 1199, '📸'),
  ('Rose Anniversary Cake (1kg)', 'Cakes', 'Anniversary', 'Rose-flavoured sponge, edible petals', 999, '🌹'),
  ('Spiderman Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Web-design fondant cake', 1399, '🕷️'),
  ('Unicorn Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Pastel rainbow mane, edible horn', 1499, '🦄'),
  ('Princess Castle Cake (1.5kg)', 'Cakes', 'Kids & Theme', '3D castle design, edible glitter', 1899, '👑'),
  ('Car Racing Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Race track design for little racers', 1399, '🏎️'),
  ('Dinosaur Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Jurassic jungle fondant scene', 1399, '🦕'),
  ('Football Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Stadium design with team colours', 1299, '⚽'),
  ('Minion Theme Cake (1kg)', 'Cakes', 'Kids & Theme', 'Yellow minion fondant figures', 1399, '🍌'),
  ('A4 Photo Cake (1kg)', 'Cakes', 'Photo Cake', 'Full sheet edible photo print', 1199, '📷'),
  ('Photo Cupcakes (Box of 6)', 'Cakes', 'Photo Cake', 'Mini edible photo prints', 599, '🧁'),
  ('Collage Photo Cake (1.5kg)', 'Cakes', 'Photo Cake', 'Multiple photos in one design', 1599, '🖼️'),
  ('Eggless Chocolate Truffle Cake (1kg)', 'Cakes', 'Eggless', '100% egg-free, rich chocolate', 949, '🍫'),
  ('Eggless Vanilla Cake (1kg)', 'Cakes', 'Eggless', 'Soft eggless vanilla sponge', 749, '🍰'),
  ('Eggless Red Velvet Cake (1kg)', 'Cakes', 'Eggless', 'Egg-free with cream cheese frosting', 999, '❤️'),
  ('Eggless Fresh Fruit Cake (1kg)', 'Cakes', 'Eggless', 'Seasonal fruits, whipped cream', 849, '🍓'),
  ('Eggless Black Forest Cake (1kg)', 'Cakes', 'Eggless', 'Egg-free cherries & chocolate', 899, '🍒'),
  ('Eggless Butterscotch Cake (1kg)', 'Cakes', 'Eggless', 'Praline crunch, egg-free', 849, '🧈'),
  ('Baby Shower Cake — It''s a Girl (1kg)', 'Cakes', 'Baby Shower', 'Pink theme with baby feet', 1099, '👧'),
  ('Baby Shower Cake — It''s a Boy (1kg)', 'Cakes', 'Baby Shower', 'Blue theme with baby feet', 1099, '👦'),
  ('Teddy Bear Baby Cake (1kg)', 'Cakes', 'Baby Shower', '3D teddy bear fondant topper', 1299, '🧸'),
  ('Stork Delivery Cake (1kg)', 'Cakes', 'Baby Shower', 'Stork carrying baby bundle design', 1199, '🕊️'),
  ('Graduation Cap Cake (1kg)', 'Cakes', 'Congratulations', 'Cap & scroll fondant topper', 1099, '🎓'),
  ('New Job Congrats Cake (1kg)', 'Cakes', 'Congratulations', '"Congrats" message cake', 899, '🎉'),
  ('Promotion Celebration Cake (1kg)', 'Cakes', 'Congratulations', 'Corporate-themed design', 999, '📈'),
  ('Success Star Cake (1kg)', 'Cakes', 'Congratulations', 'Gold star fondant accents', 949, '⭐'),
  ('Farewell Message Cake (1kg)', 'Cakes', 'Farewell', 'Custom "We''ll Miss You" print', 899, '👋'),
  ('Bon Voyage Cake (1kg)', 'Cakes', 'Farewell', 'Travel-themed fondant design', 999, '✈️'),
  ('Miss You Already Cake (1kg)', 'Cakes', 'Farewell', 'Heartfelt farewell design', 899, '💔'),
  ('Heart Red Velvet Valentine Cake (1kg)', 'Cakes', 'Valentine', 'Classic heart shape', 999, '💘'),
  ('Rose Theme Valentine Cake (1kg)', 'Cakes', 'Valentine', 'Edible rose garden design', 1199, '🌹'),
  ('Chocolate Love Cake (1kg)', 'Cakes', 'Valentine', 'Rich dark chocolate, heart topper', 1099, '💝'),
  ('Pull-Me-Up Surprise Cake (1kg)', 'Cakes', 'Birthday', 'Hidden treats burst out when cut', 1399, '🎊'),
  ('Pinata Cake — Kids Surprise (1.5kg)', 'Cakes', 'Kids & Theme', 'Candy-filled surprise cake', 1699, '🍬');

-- Gifts (54 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Personalised Birthday Mug', 'Gifts', 'Birthday', 'Photo print with name', 399, '☕'),
  ('Birthday Wish Jar', 'Gifts', 'Birthday', '365 handwritten wish notes', 599, '🫙'),
  ('Custom Name Necklace', 'Gifts', 'Birthday', 'Sterling silver, engraved', 1299, '📿'),
  ('Bluetooth Speaker (Portable)', 'Gifts', 'Birthday', 'Compact, 10hr battery', 1599, '🔊'),
  ('Birthday Gift Box (Chocolates + Card)', 'Gifts', 'Birthday', 'Curated combo', 699, '🎁'),
  ('Polaroid Photo Album', 'Gifts', 'Birthday', 'Handmade scrapbook style', 549, '📔'),
  ('Silver Plated Dinner Set', 'Gifts', 'Wedding', '6-piece wedding gift set', 3499, '🍽️'),
  ('Personalised Couple Photo Frame', 'Gifts', 'Wedding', 'Wooden, engraved names', 899, '🖼️'),
  ('Wedding Gift Hamper (Dry Fruits + Sweets)', 'Gifts', 'Wedding', 'Premium combo', 1999, '🎁'),
  ('Brass Decorative Showpiece', 'Gifts', 'Wedding', 'Handcrafted traditional piece', 1499, '🏺'),
  ('Cushion Covers (Set of 5, Wedding Print)', 'Gifts', 'Wedding', 'Embroidered design', 899, '🛋️'),
  ('Silver Coin (Wedding Blessing, 10g)', 'Gifts', 'Wedding', '999 fine silver', 899, '🪙'),
  ('Anniversary Photo Collage Frame', 'Gifts', 'Anniversary', 'Multi-photo wooden frame', 999, '🖼️'),
  ('Couple Watch Set', 'Gifts', 'Anniversary', 'His & hers matching watches', 2499, '⌚'),
  ('Personalised Anniversary Album', 'Gifts', 'Anniversary', 'Leather-bound photo book', 1299, '📖'),
  ('Rose Gold Jewellery Box', 'Gifts', 'Anniversary', 'Velvet-lined, engravable', 1099, '💍'),
  ('Wine Glass Set (Engraved, Pair)', 'Gifts', 'Anniversary', 'Crystal glass, personalised', 899, '🥂'),
  ('Rakhi Thali Set (Pooja + Rakhi)', 'Gifts', 'Rakhi', 'Complete rakhi ceremony kit', 449, '🪢'),
  ('Designer Rakhi (Pack of 2)', 'Gifts', 'Rakhi', 'Kundan & thread work', 199, '🪢'),
  ('Rakhi Gift Hamper for Brother', 'Gifts', 'Rakhi', 'Sweets, rakhi, dry fruits', 899, '🎁'),
  ('Kids Rakhi (Cartoon Character)', 'Gifts', 'Rakhi', 'Fun rakhi for little brothers', 99, '🎈'),
  ('Rakhi with Chocolate Box', 'Gifts', 'Rakhi', 'Rakhi + assorted chocolates', 349, '🍫'),
  ('Silver Rakhi (Oxidised)', 'Gifts', 'Rakhi', 'Traditional silver design', 599, '🪢'),
  ('Diwali Gift Box (Dry Fruits + Diyas)', 'Gifts', 'Diwali', 'Festive combo', 999, '🪔'),
  ('Diwali Sweets & Chocolate Hamper', 'Gifts', 'Diwali', 'Assorted mithai + chocolate', 899, '🍬'),
  ('Brass Diya Gift Set (Pair)', 'Gifts', 'Diwali', 'Decorative brass diyas', 449, '🪔'),
  ('Diwali Puja Thali Gift Set', 'Gifts', 'Diwali', 'Complete puja gift kit', 699, '🙏'),
  ('Scented Candle Diwali Gift Pack', 'Gifts', 'Diwali', 'Set of 4 festive scents', 549, '🕯️'),
  ('Housewarming Plant Gift Set', 'Gifts', 'Housewarming', 'Money plant in ceramic pot', 449, '🪴'),
  ('Decorative Wall Clock', 'Gifts', 'Housewarming', 'Wooden, modern design', 899, '🕰️'),
  ('Kitchen Essentials Gift Hamper', 'Gifts', 'Housewarming', 'Spice rack + accessories', 1299, '🍳'),
  ('Welcome Home Doormat & Diya Set', 'Gifts', 'Housewarming', 'Traditional entrance combo', 399, '🏠'),
  ('Baby Welcome Gift Set', 'Gifts', 'Baby Shower', 'Onesies, cap, mittens', 999, '👶'),
  ('Personalised Baby Blanket', 'Gifts', 'Baby Shower', 'Embroidered with name', 799, '🍼'),
  ('New Mom Care Hamper', 'Gifts', 'Baby Shower', 'Skincare + comfort items', 1199, '🎀'),
  ('Baby Photo Frame Set', 'Gifts', 'Baby Shower', 'Milestone photo frames', 599, '📷'),
  ('Corporate Gift Set (Pen + Diary)', 'Gifts', 'Corporate', 'Premium branded set', 799, '💼'),
  ('Executive Desk Organiser', 'Gifts', 'Corporate', 'Wood & leather finish', 999, '🗂️'),
  ('Corporate Diwali Hamper', 'Gifts', 'Corporate', 'Dry fruits, premium packaging', 1499, '🎁'),
  ('Customised Coffee Table Book', 'Gifts', 'Corporate', 'Branded corporate gift', 1299, '📚'),
  ('Premium Pen Gift Box', 'Gifts', 'Corporate', 'Metal body, engravable', 699, '🖊️'),
  ('Get Well Soon Flower & Card Combo', 'Gifts', 'Get Well', 'Cheerful bouquet + card', 599, '🌻'),
  ('Get Well Care Package', 'Gifts', 'Get Well', 'Soup mix, tea, comfort items', 799, '🍵'),
  ('Get Well Soon Balloon Bouquet', 'Gifts', 'Get Well', 'Uplifting balloon set', 449, '🎈'),
  ('Farewell Memory Book', 'Gifts', 'Farewell', 'Signed messages keepsake', 599, '📔'),
  ('Farewell Gift Hamper', 'Gifts', 'Farewell', 'Chocolates + card + keepsake', 899, '🎁'),
  ('Travel Organiser Kit (Farewell Gift)', 'Gifts', 'Farewell', 'Practical travel gift', 999, '🧳'),
  ('Valentine Teddy Bear (Large)', 'Gifts', 'Valentine', 'Soft plush, 3 feet', 799, '🧸'),
  ('Personalised Love Photo Frame', 'Gifts', 'Valentine', 'Couple photo, engraved', 699, '💕'),
  ('Valentine Chocolate Gift Box', 'Gifts', 'Valentine', 'Premium assorted chocolates', 649, '🍫'),
  ('Rose & Chocolate Combo', 'Gifts', 'Valentine', '6 roses + choco box', 599, '🌹'),
  ('Couple Keychain Set', 'Gifts', 'Valentine', 'Matching engraved keychains', 349, '🔑'),
  ('Congratulations Gift Box', 'Gifts', 'Congratulations', 'Curated celebratory combo', 799, '🎉'),
  ('Success Trophy (Personalised)', 'Gifts', 'Congratulations', 'Engraved acrylic trophy', 899, '🏆');

-- Flowers (52 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Birthday Mixed Bouquet (20 stems)', 'Flowers', 'Birthday', 'Gerberas, roses, lilies', 899, '💐'),
  ('Balloon & Flower Combo', 'Flowers', 'Birthday', 'Bouquet + birthday balloons', 999, '🎈'),
  ('Birthday Basket Arrangement', 'Flowers', 'Birthday', 'Seasonal flowers in basket', 799, '🧺'),
  ('Chocolate & Flower Bouquet', 'Flowers', 'Birthday', 'Roses + chocolate box combo', 899, '🍫'),
  ('Exotic Lily Bouquet (10 stems)', 'Flowers', 'Birthday', 'Fragrant white lilies', 999, '🤍'),
  ('Gerbera Delight Bouquet', 'Flowers', 'Birthday', 'Colourful gerbera daisies', 549, '🌼'),
  ('Bridal Bouquet (White Roses)', 'Flowers', 'Wedding', 'Classic bridal hand-tied', 1299, '💍'),
  ('Wedding Mandap Flower Décor Pack', 'Flowers', 'Wedding', 'Fresh flowers for mandap', 4999, '🌸'),
  ('Rose Petal Bags (For Showering)', 'Flowers', 'Wedding', '5kg fresh petals', 799, '🌹'),
  ('Wedding Car Decoration Flowers', 'Flowers', 'Wedding', 'Fresh garlands & bouquets', 1499, '🚗'),
  ('Groom Boutonniere & Bride Bouquet Combo', 'Flowers', 'Wedding', 'Matching set', 999, '🤵'),
  ('Anniversary Red Rose Bouquet (25 stems)', 'Flowers', 'Anniversary', 'Deep red roses', 1299, '❤️'),
  ('Anniversary Orchid Arrangement', 'Flowers', 'Anniversary', 'Premium purple orchids', 1499, '🌺'),
  ('Vase Arrangement (Mixed Premium)', 'Flowers', 'Anniversary', 'Glass vase included', 1099, '🏺'),
  ('Forever Love Bouquet (50 Roses)', 'Flowers', 'Anniversary', 'Grand gesture bouquet', 2499, '💕'),
  ('Tulip Bouquet (Imported, 15 stems)', 'Flowers', 'Anniversary', 'Fresh imported tulips', 1699, '🌷'),
  ('White Lily Sympathy Wreath', 'Flowers', 'Sympathy', 'Condolence arrangement', 1499, '🤍'),
  ('White Rose Sympathy Bouquet', 'Flowers', 'Sympathy', 'Elegant, respectful design', 999, '🕊️'),
  ('Sympathy Standing Basket', 'Flowers', 'Sympathy', 'Tall floral tribute', 1899, '🌿'),
  ('Peace Lily Plant (Sympathy Gift)', 'Flowers', 'Sympathy', 'Living memorial plant', 799, '🪴'),
  ('Valentine Red Roses (50 stems)', 'Flowers', 'Valentine', 'Grand romantic bouquet', 2199, '❤️'),
  ('Heart-Shaped Rose Arrangement', 'Flowers', 'Valentine', 'Roses arranged in heart', 1599, '💘'),
  ('Valentine Mixed Bouquet with Teddy', 'Flowers', 'Valentine', 'Roses + teddy combo', 1099, '🧸'),
  ('Single Rose Elegant Box', 'Flowers', 'Valentine', 'Premium boxed rose', 399, '🌹'),
  ('Valentine Carnation Bouquet', 'Flowers', 'Valentine', 'Pink & red carnations', 749, '🌸'),
  ('Get Well Cheerful Bouquet', 'Flowers', 'Get Well', 'Bright sunflowers & daisies', 649, '🌻'),
  ('Get Well Soon Plant Gift', 'Flowers', 'Get Well', 'Low-maintenance succulent', 449, '🌵'),
  ('Fruit & Flower Basket', 'Flowers', 'Get Well', 'Fresh fruits with blooms', 1099, '🍎'),
  ('Congratulations Bouquet (Mixed Bright)', 'Flowers', 'Congratulations', 'Cheerful colours', 799, '🎉'),
  ('New Job Success Bouquet', 'Flowers', 'Congratulations', 'Yellow & orange florals', 749, '💼'),
  ('Graduation Flower Bouquet', 'Flowers', 'Congratulations', 'Academic-themed arrangement', 849, '🎓'),
  ('Grand Opening Flower Stand', 'Flowers', 'Congratulations', 'Large celebratory display', 2999, '🎊'),
  ('Housewarming Orchid Plant', 'Flowers', 'Housewarming', 'Potted phalaenopsis orchid', 899, '🪴'),
  ('Lucky Bamboo Arrangement', 'Flowers', 'Housewarming', 'Feng shui bamboo plant', 449, '🎍'),
  ('Money Plant in Ceramic Pot', 'Flowers', 'Housewarming', 'Auspicious housewarming gift', 399, '🌱'),
  ('Fresh Marigold Garland (Pair)', 'Flowers', 'Daily & Pooja', 'For everyday pooja/decor', 149, '🌼'),
  ('Mixed Seasonal Flower Bunch', 'Flowers', 'Daily & Pooja', 'Everyday fresh flowers', 349, '💐'),
  ('Single Stem Rose (Daily Gifting)', 'Flowers', 'Daily & Pooja', 'Individually wrapped', 99, '🌹'),
  ('Jasmine Gajra (String)', 'Flowers', 'Daily & Pooja', 'Fresh fragrant jasmine', 79, '🤍'),
  ('Carnation Bunch (10 stems)', 'Flowers', 'Daily & Pooja', 'Long-lasting carnations', 449, '🌸'),
  ('Daisy Bouquet (Cheerful)', 'Flowers', 'Daily & Pooja', 'Simple everyday joy', 399, '🌼'),
  ('Lotus Flowers (Pair, Pooja)', 'Flowers', 'Daily & Pooja', 'Fresh lotus for worship', 199, '🪷'),
  ('Diwali Marigold & Rose Torans (Pair)', 'Flowers', 'Festive', 'Door decoration', 299, '🪔'),
  ('Navratri Flower Garland Set', 'Flowers', 'Festive', 'Festive door/mandap décor', 349, '💃'),
  ('Ganesh Chaturthi Flower Decoration Pack', 'Flowers', 'Festive', 'For pandal/home', 799, '🐘'),
  ('Festive Flower Rangoli Kit', 'Flowers', 'Festive', 'Fresh petals for rangoli', 449, '🎨'),
  ('Temple Flower Offering Basket', 'Flowers', 'Festive', 'Daily worship flowers', 249, '🙏'),
  ('Baby Shower Pastel Bouquet', 'Flowers', 'Baby Shower', 'Soft pink/blue blooms', 799, '🍼'),
  ('It''s a Girl Flower Arrangement', 'Flowers', 'Baby Shower', 'Pink themed bouquet', 849, '👧'),
  ('It''s a Boy Flower Arrangement', 'Flowers', 'Baby Shower', 'Blue themed bouquet', 849, '👦'),
  ('Farewell Bouquet (Mixed Elegant)', 'Flowers', 'Farewell', 'Thoughtful sendoff', 749, '👋'),
  ('Bon Voyage Flower Box', 'Flowers', 'Farewell', 'Travel-themed arrangement', 899, '✈️');

-- Hampers (52 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Diwali Dry Fruit Hamper (Premium)', 'Hampers', 'Diwali', 'Almonds, cashews, pistachios', 1499, '🪔'),
  ('Diwali Sweets Hamper', 'Hampers', 'Diwali', 'Assorted traditional mithai', 999, '🍬'),
  ('Diwali Chocolate Gift Hamper', 'Hampers', 'Diwali', 'Premium chocolate assortment', 899, '🍫'),
  ('Diwali Puja & Sweets Combo Hamper', 'Hampers', 'Diwali', 'Diyas + prasad sweets', 799, '🙏'),
  ('Diwali Deluxe Gift Hamper (Grand)', 'Hampers', 'Diwali', 'Dry fruits + sweets + diyas', 2499, '✨'),
  ('Diwali Tea & Snacks Hamper', 'Hampers', 'Diwali', 'Premium tea with namkeen', 699, '🫖'),
  ('Rakhi Special Dry Fruit Hamper', 'Hampers', 'Rakhi', 'For brothers, premium mix', 999, '🪢'),
  ('Rakhi Chocolate & Sweets Hamper', 'Hampers', 'Rakhi', 'Rakhi + assorted treats', 649, '🍬'),
  ('Rakhi Gift Hamper for Sister', 'Hampers', 'Rakhi', 'Cosmetics + chocolates', 899, '💝'),
  ('Rakhi Combo Hamper (Kids)', 'Hampers', 'Rakhi', 'Toys + rakhi + sweets', 549, '🧸'),
  ('Premium Rakhi Hamper (Dry Fruits + Silver Coin)', 'Hampers', 'Rakhi', 'Grand gesture hamper', 1499, '🪙'),
  ('New Year Celebration Hamper', 'Hampers', 'New Year', 'Wine glasses + snacks + cake', 1799, '🎆'),
  ('New Year Chocolate Hamper', 'Hampers', 'New Year', 'Premium imported chocolates', 999, '🍫'),
  ('New Year Party Hamper (Snacks + Mixers)', 'Hampers', 'New Year', 'Party-ready combo', 1299, '🥂'),
  ('New Year Wellness Hamper', 'Hampers', 'New Year', 'Health foods, resolutions kit', 899, '🍎'),
  ('Wedding Congratulations Hamper', 'Hampers', 'Wedding', 'Dry fruits + sweets + card', 1499, '💍'),
  ('Bridal Shower Hamper', 'Hampers', 'Wedding', 'Pampering essentials for bride', 1699, '👰'),
  ('Wedding Guest Return Gift Hamper (Set of 10)', 'Hampers', 'Wedding', 'Bulk favours', 2999, '🎁'),
  ('Wedding Anniversary Hamper', 'Hampers', 'Wedding', 'Wine, chocolates, photo frame', 1899, '💕'),
  ('Groom''s Special Grooming Hamper', 'Hampers', 'Wedding', 'Premium grooming kit', 1399, '🤵'),
  ('Corporate Diwali Hamper (Bulk-Ready)', 'Hampers', 'Corporate', 'Premium branding-ready', 1999, '💼'),
  ('Corporate Welcome Kit Hamper', 'Hampers', 'Corporate', 'New employee essentials', 1299, '🗂️'),
  ('Corporate Appreciation Hamper', 'Hampers', 'Corporate', 'Gourmet snacks + card', 1599, '🏆'),
  ('Client Gifting Hamper (Premium)', 'Hampers', 'Corporate', 'Dry fruits + premium tea', 2199, '🎁'),
  ('Corporate New Year Hamper (Bulk)', 'Hampers', 'Corporate', 'Festive branded packaging', 1799, '🎄'),
  ('Get Well Soon Wellness Hamper', 'Hampers', 'Get Well', 'Soups, herbal tea, honey', 899, '🍵'),
  ('Recovery Care Package', 'Hampers', 'Get Well', 'Comfort foods + get-well card', 749, '💊'),
  ('Immunity Boost Hamper', 'Hampers', 'Get Well', 'Health drinks, dry fruits, fruits', 1099, '🍊'),
  ('Birthday Celebration Hamper', 'Hampers', 'Birthday', 'Cake, balloons, chocolates', 1299, '🎂'),
  ('Kids Birthday Surprise Hamper', 'Hampers', 'Birthday', 'Toys + chocolates + card', 899, '🎁'),
  ('Birthday Spa & Relax Hamper', 'Hampers', 'Birthday', 'Pampering self-care combo', 1199, '🧖'),
  ('Milestone Birthday Deluxe Hamper', 'Hampers', 'Birthday', '18th/21st/50th special', 1899, '🎉'),
  ('Ferrero Rocher Gift Hamper', 'Hampers', 'Chocolate', 'Premium branded chocolates', 999, '🍫'),
  ('Assorted Truffle Chocolate Box', 'Hampers', 'Chocolate', 'Handmade truffle collection', 799, '🍬'),
  ('Dark Chocolate Lover''s Hamper', 'Hampers', 'Chocolate', 'Premium dark chocolate mix', 899, '🖤'),
  ('Belgian Chocolate Gift Box', 'Hampers', 'Chocolate', 'Imported Belgian chocolates', 1499, '🍫'),
  ('Homestyle Chocolate Barfi Hamper', 'Hampers', 'Chocolate', 'Traditional Indian sweets', 649, '🍮'),
  ('Premium Dry Fruit Box (1kg)', 'Hampers', 'Dry Fruits', 'Almonds, cashews, walnuts, pistachios', 1299, '🥜'),
  ('Mixed Dry Fruit Gift Tray', 'Hampers', 'Dry Fruits', 'Decorative festive tray', 999, '🎁'),
  ('Saffron & Dry Fruit Combo', 'Hampers', 'Dry Fruits', 'Premium kesar included', 1599, '🌾'),
  ('Dates & Dry Fruit Hamper', 'Hampers', 'Dry Fruits', 'Healthy festive combo', 899, '🍯'),
  ('Exotic Nuts Gift Box', 'Hampers', 'Dry Fruits', 'Pine nuts, macadamia, pistachios', 1799, '🌰'),
  ('Housewarming Sweets & Décor Hamper', 'Hampers', 'Housewarming', 'Mithai + diya set', 999, '🏠'),
  ('Griha Pravesh Gift Hamper', 'Hampers', 'Housewarming', 'Traditional welcome combo', 1199, '🙏'),
  ('New Home Essentials Hamper', 'Hampers', 'Housewarming', 'Kitchen basics + sweets', 1399, '🍳'),
  ('Anniversary Wine & Chocolate Hamper', 'Hampers', 'Anniversary', 'Premium celebratory combo', 1599, '🍷'),
  ('Silver Jubilee Gift Hamper', 'Hampers', 'Anniversary', 'Elegant 25th anniversary combo', 1999, '🥈'),
  ('Romantic Couple Hamper', 'Hampers', 'Anniversary', 'Wine, chocolates, candles', 1499, '💑'),
  ('Baby Shower Gift Hamper', 'Hampers', 'Baby Shower', 'Baby essentials + sweets', 1399, '👶'),
  ('New Mom Pampering Hamper', 'Hampers', 'Baby Shower', 'Self-care + comfort combo', 1299, '🎀'),
  ('Welcome Baby Hamper (Deluxe)', 'Hampers', 'Baby Shower', 'Clothes, toys, keepsakes', 1899, '🍼'),
  ('Baby Shower Snacks & Sweets Hamper', 'Hampers', 'Baby Shower', 'Celebration treats', 899, '🍭');

-- Party Essentials (52 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Happy Birthday Foil Balloon Set', 'Party Essentials', 'Birthday', 'Letter balloons spelling name', 399, '🎈'),
  ('Birthday Photo Booth Props Kit', 'Party Essentials', 'Birthday', '20-piece prop set', 349, '📸'),
  ('Number Foil Balloons (Giant, 40 inch)', 'Party Essentials', 'Birthday', 'Age number balloon', 249, '🔢'),
  ('Birthday Party Hats (Pack of 10)', 'Party Essentials', 'Birthday', 'Colourful cone hats', 199, '🎉'),
  ('LED Fairy Lights (Birthday Decor)', 'Party Essentials', 'Birthday', 'Warm white, 10m', 299, '✨'),
  ('Birthday Table Centerpiece Kit', 'Party Essentials', 'Birthday', 'Themed centerpiece decor', 449, '🎀'),
  ('Confetti Balloon Set (Clear, 5pc)', 'Party Essentials', 'Birthday', 'Gold confetti-filled', 349, '🎊'),
  ('Baby Shower Balloon Arch Kit', 'Party Essentials', 'Baby Shower', 'Pastel balloon garland', 899, '🎈'),
  ('Its a Boy/Girl Banner Set', 'Party Essentials', 'Baby Shower', 'Reveal party banner', 249, '🍼'),
  ('Baby Shower Photo Backdrop', 'Party Essentials', 'Baby Shower', 'Cloud & stars theme', 799, '☁️'),
  ('Baby Shower Party Favors (Set of 20)', 'Party Essentials', 'Baby Shower', 'Mini thank-you gifts', 599, '🎁'),
  ('Gender Reveal Balloon (Pop Confetti)', 'Party Essentials', 'Baby Shower', 'Blue/pink powder pop', 449, '💥'),
  ('Baby Shower Tableware Set', 'Party Essentials', 'Baby Shower', 'Plates, cups, napkins', 549, '🍽️'),
  ('Anniversary Balloon Bouquet', 'Party Essentials', 'Anniversary', 'Gold & rose gold balloons', 549, '💕'),
  ('Anniversary Photo Backdrop Banner', 'Party Essentials', 'Anniversary', 'Custom years banner', 699, '🖼️'),
  ('LED Number Lights (Anniversary Years)', 'Party Essentials', 'Anniversary', 'Marquee style', 899, '💡'),
  ('Anniversary Table Décor Set', 'Party Essentials', 'Anniversary', 'Candles, runner, centerpieces', 799, '🕯️'),
  ('Griha Pravesh Décor Kit', 'Party Essentials', 'Housewarming', 'Traditional entrance decoration', 699, '🏠'),
  ('Housewarming Toran & Rangoli Kit', 'Party Essentials', 'Housewarming', 'Door & floor decor combo', 449, '🎨'),
  ('Welcome Home Balloon Set', 'Party Essentials', 'Housewarming', '"Welcome Home" banner + balloons', 399, '🎈'),
  ('Superhero Theme Party Kit', 'Party Essentials', 'Theme Party', 'Banners, balloons, masks', 999, '🦸'),
  ('Spiderman Party Decoration Set', 'Party Essentials', 'Theme Party', 'Full theme package', 899, '🕷️'),
  ('Superhero Cape & Mask (Set of 6)', 'Party Essentials', 'Theme Party', 'Party favors for kids', 599, '🦹'),
  ('Avengers Theme Balloon Bouquet', 'Party Essentials', 'Theme Party', 'Character balloons', 699, '🛡️'),
  ('Princess Theme Party Decoration Kit', 'Party Essentials', 'Theme Party', 'Pink & gold full set', 1099, '👑'),
  ('Unicorn Theme Balloon Garland', 'Party Essentials', 'Theme Party', 'Pastel rainbow arch', 899, '🦄'),
  ('Unicorn Party Favor Bags (Set of 10)', 'Party Essentials', 'Theme Party', 'Themed goodie bags', 449, '🎒'),
  ('Princess Crown & Wand Set (Pack of 6)', 'Party Essentials', 'Theme Party', 'Party favors', 399, '👸'),
  ('Unicorn Photo Backdrop', 'Party Essentials', 'Theme Party', 'Glittery rainbow backdrop', 799, '🌈'),
  ('Jungle Safari Theme Decoration Kit', 'Party Essentials', 'Theme Party', 'Animal print banners', 899, '🦁'),
  ('Dinosaur Theme Party Set', 'Party Essentials', 'Theme Party', 'Balloons + banner + props', 799, '🦕'),
  ('Jungle Animal Balloon Set', 'Party Essentials', 'Theme Party', 'Safari-themed balloons', 549, '🐘'),
  ('Balloon Arch Kit (100pc DIY)', 'Party Essentials', 'Balloon Decor', 'Complete DIY arch kit', 699, '🎈'),
  ('Chrome Balloon Set (Metallic, 20pc)', 'Party Essentials', 'Balloon Decor', 'Gold/silver/rose gold', 449, '✨'),
  ('Helium Balloon Bouquet (Ready-to-Pickup)', 'Party Essentials', 'Balloon Decor', 'Pre-inflated set', 599, '🎈'),
  ('Star Foil Balloons (Set of 5)', 'Party Essentials', 'Balloon Decor', 'Gold star shapes', 299, '⭐'),
  ('Balloon Weight & Ribbon Kit', 'Party Essentials', 'Balloon Decor', 'Accessories for balloon setup', 149, '🎀'),
  ('Giant Balloon (36 inch, Round)', 'Party Essentials', 'Balloon Decor', 'Statement balloon piece', 199, '🔴'),
  ('Customisable Photo Backdrop (Any Text)', 'Party Essentials', 'Backdrop & Banners', 'Personalised backdrop', 999, '🖼️'),
  ('Sequin Backdrop Curtain (Gold)', 'Party Essentials', 'Backdrop & Banners', 'Shimmer wall backdrop', 799, '✨'),
  ('Fairy Light Curtain Backdrop', 'Party Essentials', 'Backdrop & Banners', 'Twinkling light wall', 899, '💫'),
  ('Floral Backdrop Panel', 'Party Essentials', 'Backdrop & Banners', 'Artificial flower wall', 1299, '🌸'),
  ('Engagement Decoration Kit', 'Party Essentials', 'Wedding & Engagement', 'Rings backdrop + balloons', 1499, '💍'),
  ('Wedding Welcome Signage', 'Party Essentials', 'Wedding & Engagement', 'Personalised couple names', 899, '💒'),
  ('Sangeet Party Decor Kit', 'Party Essentials', 'Wedding & Engagement', 'Colourful festive décor set', 1299, '💃'),
  ('Bridal Shower Decoration Kit', 'Party Essentials', 'Wedding & Engagement', 'Elegant pastel theme', 999, '👰'),
  ('Farewell Party Decoration Kit', 'Party Essentials', 'Farewell', '"We''ll Miss You" banner set', 599, '👋'),
  ('Retirement Party Decor Set', 'Party Essentials', 'Farewell', 'Celebratory gold theme', 699, '🎊'),
  ('Disposable Cutlery Set (Party Pack)', 'Party Essentials', 'Tableware', 'Spoons, forks, knives', 249, '🍴'),
  ('Themed Paper Napkins (Pack of 50)', 'Party Essentials', 'Tableware', 'Assorted prints', 149, '🧻'),
  ('Cake Stand (Decorative, Reusable)', 'Party Essentials', 'Tableware', 'Elegant display stand', 449, '🎂'),
  ('Party Streamers & Confetti Combo', 'Party Essentials', 'Tableware', 'Multi-colour set', 199, '🎉');

-- Pooja & Essentials (52 items)
INSERT INTO products (name, category, occasion, description, price, emoji) VALUES
  ('Cotton Wicks (Batti, Pack of 100)', 'Pooja & Essentials', 'Daily Pooja', 'For daily diya lighting', 30, '🪔'),
  ('Pure Ghee for Diya (200ml)', 'Pooja & Essentials', 'Daily Pooja', 'Cow ghee for daily pooja', 180, '🧈'),
  ('Til Oil for Diya (200ml)', 'Pooja & Essentials', 'Daily Pooja', 'Sesame oil, traditional', 90, '🛢️'),
  ('Daily Pooja Samagri Kit', 'Pooja & Essentials', 'Daily Pooja', 'Basic everyday essentials combo', 250, '🙏'),
  ('Small Brass Diya (Single)', 'Pooja & Essentials', 'Daily Pooja', 'Everyday use diya', 60, '🪔'),
  ('Pooja Aasan (Mat)', 'Pooja & Essentials', 'Daily Pooja', 'Cotton prayer seat mat', 199, '🧘'),
  ('Incense Holder (Brass Agarbatti Stand)', 'Pooja & Essentials', 'Daily Pooja', 'Traditional stand', 120, '🕯️'),
  ('Daily Puja Flowers (Loose, 250g)', 'Pooja & Essentials', 'Daily Pooja', 'Fresh mixed flowers', 60, '🌼'),
  ('Diwali Rangoli Colours Set', 'Pooja & Essentials', 'Diwali', 'Vibrant powder colours', 199, '🎨'),
  ('Lakshmi-Ganesh Idol Set (Diwali Pooja)', 'Pooja & Essentials', 'Diwali', 'Clay/brass idols', 599, '🪷'),
  ('Diwali Special Diya Set (Decorative, 21pc)', 'Pooja & Essentials', 'Diwali', 'Painted clay diyas', 349, '🪔'),
  ('Diwali Puja Vidhi Kit (Complete)', 'Pooja & Essentials', 'Diwali', 'Full Lakshmi puja samagri', 799, '🙏'),
  ('Torans for Diwali (Mango Leaf + Marigold)', 'Pooja & Essentials', 'Diwali', 'Door decoration', 149, '🌿'),
  ('Diwali Aarti Thali Set (Decorated)', 'Pooja & Essentials', 'Diwali', 'Festive decorated thali', 499, '🍽️'),
  ('Eco-Friendly Ganesh Idol (Clay, Medium)', 'Pooja & Essentials', 'Ganesh Chaturthi', 'Immersion-friendly', 899, '🐘'),
  ('Ganesh Chaturthi Pooja Samagri Kit', 'Pooja & Essentials', 'Ganesh Chaturthi', 'Complete festival kit', 649, '🙏'),
  ('Modak Making Kit + Ingredients', 'Pooja & Essentials', 'Ganesh Chaturthi', 'For prasad preparation', 299, '🍡'),
  ('Ganpati Decoration Mandap Kit', 'Pooja & Essentials', 'Ganesh Chaturthi', 'Home mandap decoration', 1299, '🏛️'),
  ('Durva Grass & Red Hibiscus Set', 'Pooja & Essentials', 'Ganesh Chaturthi', 'Essential Ganesh offerings', 79, '🌿'),
  ('Navratri Kalash Sthapana Kit', 'Pooja & Essentials', 'Navratri', 'Complete kalash setup', 449, '🏺'),
  ('Navratri Garba Dandiya Sticks (Pair)', 'Pooja & Essentials', 'Navratri', 'Decorated dandiya', 199, '💃'),
  ('Navratri 9-Day Pooja Samagri Kit', 'Pooja & Essentials', 'Navratri', 'Full nine-day essentials', 899, '🙏'),
  ('Durga Idol (Small, Navratri)', 'Pooja & Essentials', 'Navratri', 'Home puja idol', 799, '🔱'),
  ('Navratri Decorative Chunri Set', 'Pooja & Essentials', 'Navratri', 'Red chunri offering set', 149, '🧣'),
  ('Griha Pravesh Complete Pooja Kit', 'Pooja & Essentials', 'Griha Pravesh', 'Full ceremony samagri', 999, '🏠'),
  ('Vastu Kalash Set (Housewarming)', 'Pooja & Essentials', 'Griha Pravesh', 'Auspicious kalash setup', 649, '🏺'),
  ('Griha Pravesh Coconut & Mango Leaves Kit', 'Pooja & Essentials', 'Griha Pravesh', 'Essential items', 149, '🥥'),
  ('New Home Havan Kit', 'Pooja & Essentials', 'Griha Pravesh', 'Complete havan samagri', 799, '🔥'),
  ('Ashtamangal Kit (Housewarming)', 'Pooja & Essentials', 'Griha Pravesh', '8 auspicious items set', 349, '✨'),
  ('Satyanarayan Pooja Complete Kit', 'Pooja & Essentials', 'Satyanarayan Pooja', 'Full ceremony samagri', 899, '🙏'),
  ('Panchamrit Kit (Satyanarayan Special)', 'Pooja & Essentials', 'Satyanarayan Pooja', 'Milk, curd, ghee, honey', 199, '🥛'),
  ('Banana Leaves (Set of 5, Pooja)', 'Pooja & Essentials', 'Satyanarayan Pooja', 'Traditional offering leaves', 99, '🍌'),
  ('Satyanarayan Prasad Sheera Kit', 'Pooja & Essentials', 'Satyanarayan Pooja', 'Semolina prasad ingredients', 249, '🍮'),
  ('Wedding Mandap Pooja Samagri Kit', 'Pooja & Essentials', 'Wedding Pooja', 'Complete ceremony kit', 1499, '💍'),
  ('Haldi Ceremony Kit', 'Pooja & Essentials', 'Wedding Pooja', 'Turmeric paste + accessories', 349, '💛'),
  ('Mehendi Ceremony Pooja Thali', 'Pooja & Essentials', 'Wedding Pooja', 'Decorated thali for ceremony', 449, '🎨'),
  ('Saptapadi Havan Kit (Wedding)', 'Pooja & Essentials', 'Wedding Pooja', 'Seven-vow ceremony samagri', 999, '🔥'),
  ('Janmashtami Jhula (Cradle) Decoration', 'Pooja & Essentials', 'Janmashtami', 'Krishna cradle setup', 599, '🎋'),
  ('Krishna Idol Set (Janmashtami)', 'Pooja & Essentials', 'Janmashtami', 'Decorative Bal Gopal idol', 449, '🦚'),
  ('Janmashtami Pooja Samagri Kit', 'Pooja & Essentials', 'Janmashtami', 'Complete festival essentials', 549, '🙏'),
  ('Varalakshmi Vratham Kit', 'Pooja & Essentials', 'Regional & Other', 'South Indian pooja essentials', 799, '🪷'),
  ('Kalash Kalasam Decoration Set', 'Pooja & Essentials', 'Regional & Other', 'Traditional South decor', 449, '🏺'),
  ('Silver Pooja Coins (Set of 5)', 'Pooja & Essentials', 'Regional & Other', 'Lakshmi/Ganesh embossed', 599, '🪙'),
  ('Naming Ceremony Pooja Kit', 'Pooja & Essentials', 'Small Functions', 'Complete namkaran essentials', 649, '👶'),
  ('Upanayanam (Thread Ceremony) Kit', 'Pooja & Essentials', 'Small Functions', 'Sacred thread ceremony samagri', 999, '🧵'),
  ('Baby Shower (Godh Bharai) Pooja Thali', 'Pooja & Essentials', 'Small Functions', 'Decorated ceremony thali', 549, '🤰'),
  ('Ayush Homam Kit (Birthday Pooja)', 'Pooja & Essentials', 'Small Functions', 'Longevity blessing samagri', 799, '🔥'),
  ('Vehicle Pooja Kit (New Car/Bike)', 'Pooja & Essentials', 'Small Functions', 'Complete vehicle blessing kit', 349, '🚗'),
  ('Office Opening Pooja Kit', 'Pooja & Essentials', 'Small Functions', 'Business inauguration samagri', 699, '🏢'),
  ('Retirement Blessing Pooja Kit', 'Pooja & Essentials', 'Small Functions', 'Small ceremony essentials', 449, '🙏'),
  ('Silver Kalash (Small, Decorative)', 'Pooja & Essentials', 'Small Functions', 'Premium pooja accessory', 899, '🏺'),
  ('Pooja Chowki (Wooden Platform)', 'Pooja & Essentials', 'Small Functions', 'Decorated wooden pedestal', 599, '🪑');
