-- ============================================================
-- Migration 023: One photo per PRODUCT, and an honest label on it.
--
-- Migration 016 added products.image_url to stop ShopCategory.jsx firing
-- 50-70 live Unsplash searches per page load. That fixed the rate limit,
-- but 017 and 021 populated the column with category-wide UPDATEs:
--
--     UPDATE products SET image_url = '…'
--       WHERE category = 'Cakes' AND (occasion = 'Birthday');
--
-- One photo, eight birthday cakes. A customer buying "Barbie Theme Cake
-- (1.5kg)" sees a generic birthday sponge; someone buying "Unicorn Theme
-- Cake" sees the same generic birthday sponge. The catalog rows are
-- accurate — real names, weights, prices — so the only thing standing
-- between the shop and "you get what you saw" is the imagery.
--
-- This migration adds nothing but columns. Migration 024 (generated by
-- scripts/resolve-product-images.mjs) does the per-product UPDATEs, and
-- 025 adds the storage bucket that lets an admin replace a stock photo
-- with a real one.
--
-- On image_source, which is the point of this migration:
--
--   Sambramo is pre-launch. There is no confirmed bakery yet, so no photo
--   in the catalog can honestly claim to be the item that will arrive.
--   Pretending otherwise is the exact failure this work exists to remove,
--   so the schema carries the distinction explicitly rather than leaving
--   it to whoever writes the UI:
--
--     'stock'   a licensed photograph of something that looks like this
--               product. Shown to the customer as "Representative image".
--     'actual'  a photograph of the thing Sambramo will actually deliver,
--               uploaded by an admin. Shown as "Actual product photo".
--
--   Everything starts 'stock'. The admin Catalog tab (migration 025)
--   flips rows to 'actual' one at a time, and the coverage meter there
--   reads straight off this column.
--
-- image_alt exists because ProductImage.jsx currently renders alt="" on
-- every pre-resolved photo — a live accessibility defect. The resolver
-- has the description at hand, so it stores it.
--
-- Run this in: Supabase Dashboard → SQL Editor. Safe to re-run.
-- ============================================================

ALTER TABLE products ADD COLUMN IF NOT EXISTS image_source     TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_alt        TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_credit     TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_updated_at TIMESTAMPTZ;

-- Backfill before the CHECK lands, so the constraint can be validated
-- against existing rows. Every row today is a category-wide stock photo.
UPDATE products SET image_source = 'stock' WHERE image_source IS NULL;

ALTER TABLE products ALTER COLUMN image_source SET DEFAULT 'stock';

-- ADD CONSTRAINT has no IF NOT EXISTS in Postgres, so guard it the way
-- the rest of this project guards policies: drop, then create.
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_image_source_check;
ALTER TABLE products ADD  CONSTRAINT products_image_source_check
  CHECK (image_source IN ('stock', 'actual'));

-- Partial index: the admin Catalog tab's default view is "what still
-- needs a real photo", which is a scan for image_source = 'stock' over a
-- table that will be mostly 'actual' once the shoot is done.
CREATE INDEX IF NOT EXISTS idx_products_image_source_stock
  ON products (category) WHERE image_source = 'stock';

COMMENT ON COLUMN products.image_source     IS '''stock'' = licensed lookalike, shown as "Representative image". ''actual'' = photo of the real deliverable, shown as "Actual product photo".';
COMMENT ON COLUMN products.image_alt        IS 'Alt text for image_url. Set by the resolver script or by an admin on upload.';
COMMENT ON COLUMN products.image_credit     IS 'Attribution string for stock photos (e.g. "Photo by X on Pexels"). NULL for ''actual''.';
COMMENT ON COLUMN products.image_updated_at IS 'When image_url last changed. Lets the admin Catalog sort by staleness.';
