-- ══════════════════════════════════════════════════════════════════════
-- 137 · A payout can fail
-- ══════════════════════════════════════════════════════════════════════
--
-- APPLY BY HAND. Apply 136 first. PASTE THE WHOLE FILE IN ONE GO -- see
-- the warning about claim_payment below.
--
-- ── Run this first ──────────────────────────────────────────────────
--
--   SELECT DISTINCT status FROM public.payout_claims;
--
-- If anything comes back that is not requested/paid/rejected, the CHECK
-- swap below aborts and rolls the whole file back. That is safe, but it
-- reads like a mystery unless you have looked.
--
-- ── What is missing today ───────────────────────────────────────────
--
-- `payout_claims.status` is requested/paid/rejected. A transfer that
-- BOUNCES -- wrong IFSC, closed account, name mismatch -- has nowhere to
-- go. The two things an operator could do with it are both wrong:
--
--   leave it `requested`   the partner is told it is on its way, forever
--   mark it `rejected`     which means "your claim was refused", a
--                          different and untrue sentence, and one that
--                          offers the partner nothing to do
--
-- So money that visibly left and came back reads as money still moving.
--
-- ── The retry falls out of the index that is already there ──────────
--
-- `uq_claim_one_open_per_line` is PARTIAL, on status IN ('requested',
-- 'paid'). Adding 'failed' outside that set means a failed claim frees
-- its line the instant it is marked -- the partner can simply ask again,
-- `claimable()` already permits it with no edit, and the protection
-- against paying twice is untouched. `supersedes_id` keeps the chain
-- visible so nothing is mutated to achieve it.
--
-- This is the nicest property of the existing schema and this migration
-- leans on it rather than fighting it.
--
-- ── 'processing' is deliberately NOT added ──────────────────────────
--
-- There is no payout provider and no webhook, so nothing would ever set
-- it or clear it. A status nothing writes is exactly the defect
-- `booking_lines.status = 'settled'` has been since 059: a value in a
-- CHECK constraint that reads as a feature and is unreachable. It goes
-- in when something can move it.
--
-- Re-runnable.

BEGIN;

-- ── The status set ──────────────────────────────────────────────────
--
-- 091 wrote the CHECK inline, so Postgres named it
-- `payout_claims_status_check`. Both names are dropped and one explicit
-- name is added, so the next migration does not have to guess.
ALTER TABLE public.payout_claims
  DROP CONSTRAINT IF EXISTS payout_claims_status_check;
ALTER TABLE public.payout_claims
  DROP CONSTRAINT IF EXISTS payout_claims_status_allowed;
ALTER TABLE public.payout_claims
  ADD CONSTRAINT payout_claims_status_allowed
  CHECK (status IN ('requested', 'paid', 'rejected', 'failed'));

-- ── Why it failed, and which attempt this is ────────────────────────
--
-- All nullable, so no table rewrite and no lock worth worrying about.
--
-- `failure_code` is a small closed set because it drives what the app
-- offers the partner: 'bad_account' and 'name_mismatch' mean "fix your
-- details first", the rest mean "ask again". `failure_reason` is the
-- sentence they actually read, and it is free text because a bank's
-- return message is not a taxonomy.
ALTER TABLE public.payout_claims
  ADD COLUMN IF NOT EXISTS failed_at       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS failure_code    TEXT,
  ADD COLUMN IF NOT EXISTS failure_reason  TEXT,
  ADD COLUMN IF NOT EXISTS attempt         INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS supersedes_id   UUID REFERENCES public.payout_claims(id),
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

ALTER TABLE public.payout_claims
  DROP CONSTRAINT IF EXISTS payout_claims_failure_code_allowed;
ALTER TABLE public.payout_claims
  ADD CONSTRAINT payout_claims_failure_code_allowed
  CHECK (failure_code IS NULL OR failure_code IN (
    'bad_account', 'bank_rejected', 'name_mismatch',
    'upi_invalid', 'insufficient_balance', 'other'));

-- A failed claim must say so. A row sitting in 'failed' with no reason
-- is the same dead end this migration exists to close.
ALTER TABLE public.payout_claims
  DROP CONSTRAINT IF EXISTS payout_claims_failed_is_explained;
ALTER TABLE public.payout_claims
  ADD CONSTRAINT payout_claims_failed_is_explained
  CHECK (status <> 'failed' OR (failed_at IS NOT NULL AND failure_code IS NOT NULL));

CREATE INDEX IF NOT EXISTS idx_claims_supersedes
  ON public.payout_claims (supersedes_id) WHERE supersedes_id IS NOT NULL;

-- ── Idempotency ─────────────────────────────────────────────────────
--
-- Scoped to the vendor, not global. The key is generated by a client,
-- and a global unique index would let one partner's key collide with --
-- and therefore deny -- another's.
CREATE UNIQUE INDEX IF NOT EXISTS uq_claim_idempotency
  ON public.payout_claims (vendor_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ══════════════════════════════════════════════════════════════════════
-- claim_payment, with a key
-- ══════════════════════════════════════════════════════════════════════
--
-- !! DROP AND CREATE, NOT REPLACE !!
--
-- A new argument cannot be added with CREATE OR REPLACE: it creates a
-- second overload, and `claim_payment(uuid)` and
-- `claim_payment(uuid, text DEFAULT NULL)` both match a one-argument
-- call, so PostgREST answers every claim with "function is not unique".
--
-- Between the DROP and the CREATE the claim button is dead for every
-- partner. Inside one transaction nobody sees it -- but a file pasted
-- HALF WAY leaves production with no claim_payment at all. Paste all of
-- it. The DROP also discards 091's GRANT, which is re-issued at the
-- bottom; forgetting it is a function that exists and that no partner
-- may execute.
--
-- The existing call site (ClaimPayment.jsx) passes { p_line_id } only
-- and keeps working against the defaulted second parameter.
DROP FUNCTION IF EXISTS public.claim_payment(UUID);

CREATE OR REPLACE FUNCTION public.claim_payment(
  p_line_id UUID,
  p_idempotency_key TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_vendor  UUID;
  v_check   JSONB;
  v_id      UUID;
  v_prev    public.payout_claims%ROWTYPE;
  v_existing public.payout_claims%ROWTYPE;
BEGIN
  SELECT o.vendor_id INTO v_vendor
  FROM public.dispatch_offers o
  JOIN public.vendors v ON v.id = o.vendor_id
  WHERE o.line_id = p_line_id
    AND o.status = 'ACCEPTED'
    AND v.profile_id = auth.uid();

  IF v_vendor IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_yours');
  END IF;

  -- A replay is a success, not an error. The commonest cause of a
  -- second identical request is the first one's RESPONSE being lost on
  -- a bad connection -- the claim was made, and telling the partner it
  -- failed would make them ask a third time.
  IF p_idempotency_key IS NOT NULL THEN
    SELECT * INTO v_existing FROM public.payout_claims
    WHERE vendor_id = v_vendor AND idempotency_key = p_idempotency_key;

    IF FOUND THEN
      RETURN jsonb_build_object(
        'ok', true, 'replayed', true,
        'claim_id', v_existing.id,
        'amount_paise', v_existing.amount_paise,
        'destination', v_existing.destination);
    END IF;
  END IF;

  v_check := public.claimable(p_line_id);
  IF NOT (v_check->>'ok')::boolean THEN
    RETURN v_check;
  END IF;

  -- The chain. The most recent failed attempt on this line is what this
  -- one supersedes, so a partner asking twice after two bounces reads as
  -- attempt 3 of one story rather than three unrelated rows.
  SELECT * INTO v_prev FROM public.payout_claims
  WHERE line_id = p_line_id AND status = 'failed'
  ORDER BY requested_at DESC LIMIT 1;

  INSERT INTO public.payout_claims (
    line_id, vendor_id, amount_paise, method, destination,
    attempt, supersedes_id, idempotency_key)
  VALUES (
    p_line_id, v_vendor,
    (v_check->>'amount_paise')::bigint,
    v_check->>'method',
    v_check->>'destination',
    COALESCE(v_prev.attempt, 0) + 1,
    v_prev.id,
    p_idempotency_key)
  RETURNING id INTO v_id;

  PERFORM public.write_money_audit(
    'claim_created', 'claim', v_id, v_vendor, p_line_id,
    (v_check->>'amount_paise')::bigint, NULL,
    jsonb_build_object('attempt', COALESCE(v_prev.attempt, 0) + 1,
                       'destination', v_check->>'destination'),
    NULL);

  RETURN jsonb_build_object(
    'ok', true,
    'claim_id', v_id,
    'amount_paise', (v_check->>'amount_paise')::bigint,
    'destination', v_check->>'destination');

EXCEPTION
  -- The unique index did its job: two taps, one claim.
  WHEN unique_violation THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_claimed',
      'says', 'You have already claimed this one.');
END $$;

REVOKE ALL ON FUNCTION public.claim_payment(UUID, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_payment(UUID, TEXT) TO authenticated;

COMMIT;
