create table if not exists public.launch_interest (
  id bigint generated by default as identity primary key,
  email text not null,
  phone text,
  interest text not null,
  partner boolean not null default false,
  source text not null default 'sambramo-public-site',
  created_at timestamptz not null default now()
);

alter table public.launch_interest enable row level security;

create index if not exists launch_interest_email_idx
  on public.launch_interest (lower(email));

create index if not exists launch_interest_created_at_idx
  on public.launch_interest (created_at desc);

comment on table public.launch_interest is
  'Early-access interest captured from the public Sambramo launch website.';

comment on column public.launch_interest.email is
  'Contact email supplied for Sambramo launch communication.';

comment on column public.launch_interest.partner is
  'Whether the visitor expressed partner/vendor interest.';
